"""add case confidentiality and access_requests table

Revision ID: 7a1f2c9e4d3b
Revises: b586464fcb90
Create Date: 2026-09-17 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1f2c9e4d3b'
down_revision: Union[str, None] = 'b586464fcb90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('confidentiality', sa.String(), nullable=False, server_default='normal'))
    op.create_table(
        'access_requests',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('requester_user_id', sa.String(), nullable=False),
        sa.Column('target_case_id', sa.String(), nullable=False),
        sa.Column('matched_entity_id', sa.String(), nullable=False),
        sa.Column('reason', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='pending_investigator'),
        sa.Column('created_at', sa.String(), nullable=False),
        sa.Column('escalated_at', sa.String(), nullable=True),
        sa.Column('resolved_at', sa.String(), nullable=True),
        sa.Column('resolved_by_user_id', sa.String(), nullable=True),
        sa.Column('denial_note', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['requester_user_id'], ['users.id']),
        sa.ForeignKeyConstraint(['target_case_id'], ['cases.id']),
        sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_requests')
    op.drop_column('cases', 'confidentiality')
    # ### end Alembic commands ###
