"""
api/report_builder.py

Builds a case report from what is actually persisted and analysed for the
case: sources, network size, ranked key individuals with the reason each
was flagged, entities awaiting investigator review, detected patterns,
and the source documents behind each key individual.

Output formats: Markdown, CSV (entity table) and PDF (reportlab, BSD).
The PDF is the prosecutor-facing artefact from the project's personas:
a printable summary in which every claim names its source documents --
"explainable, not a risk score".

This is decision support for investigators. Nothing here predicts
anyone's future behaviour or scores an individual's likelihood of
offending; "key influencer" means network position within the case's
own evidence (see graph.build.rank_influencers).
"""

from __future__ import annotations

import csv
import io
from datetime import datetime, timezone

from sqlalchemy.orm import Session

from api.casegraph import build_case_graph
from db import repository as repo
from graph.analytics import detect_anomalies
from graph.build import rank_influencers
from schema.case import Case

DISCLAIMER = (
    "Generated by an automated analysis of the documents ingested for this case. Findings are leads for "
    "investigators to verify against the cited source documents; they are not evidence of guilt, and no "
    "individual is scored or predicted. Entities marked 'needs review' were merged on weaker evidence and "
    "should be confirmed before being relied upon."
)


def build_case_report_data(db: Session, case: Case) -> dict:
    graph, resolved, mentions = build_case_graph(db, case.id)
    sources = repo.get_document_summary_for_case(db, case.id)
    data = {
        "case": {"id": case.id, "title": case.title, "status": case.status.value, "opened_at": case.opened_at},
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "sources": sources,
        "counts": {}, "influencers": [], "review": [], "alerts": [], "entities": [], "overrides": [],
    }
    if graph is None:
        return data

    by_type: dict = {}
    for _, attrs in graph.nodes(data=True):
        by_type[attrs["entity_type"].lower()] = by_type.get(attrs["entity_type"].lower(), 0) + 1
    data["counts"] = {"entities": graph.number_of_nodes(), "relationships": graph.number_of_edges(),
                      "mentions": len(mentions), "by_type": by_type}

    for r in rank_influencers(graph, top_n=5):
        attrs = graph.nodes[r["node_id"]]
        docs = sorted(attrs.get("source_doc_ids", []))
        data["influencers"].append({
            "rank": r["rank"], "name": attrs["canonical_text"], "aliases": list(attrs.get("aliases", [])),
            "reason": r["reason"], "documents": docs, "needs_review": bool(attrs.get("needs_review")),
        })

    for e in resolved:
        entry = {"name": e.canonical_text, "type": e.entity_type.value.lower(),
                 "documents": sorted(e.source_doc_ids), "aliases": list(e.aliases),
                 "merge_confidence": round(e.merge_confidence, 2), "needs_review": e.needs_review,
                 "reasons": list(e.merge_reasons)}
        data["entities"].append(entry)
        if e.needs_review:
            data["review"].append(entry)

    docs = repo.get_documents_for_case(db, case.id)
    for f in detect_anomalies(graph, docs):
        data["alerts"].append({"type": f["type"].replace("_", " "), "detail": f["detail"],
                               "document": f.get("doc_id")})
    data["overrides"] = repo.list_resolution_overrides(db, case.id)
    return data


# ---------------------------------------------------------------------------

def to_markdown(d: dict) -> str:
    c = d["case"]
    out = [f"# Case Summary — {c['title']}", "", f"- Case ID: {c['id']}", f"- Status: {c['status']}",
           f"- Opened: {c['opened_at']}", f"- Report generated: {d['generated_at']}", "", f"> {DISCLAIMER}", ""]

    out += ["## Ingested sources", ""]
    if not d["sources"]:
        out.append("No documents ingested for this case yet.")
    else:
        out += ["| Document type | Count | Last updated |", "|---|---|---|"]
        out += [f"| {s['document_type']} | {s['count']} | {s['last_updated']} |" for s in d["sources"]]

    if d["counts"]:
        n = d["counts"]
        mix = ", ".join(f"{v} {k}" for k, v in sorted(n["by_type"].items(), key=lambda kv: -kv[1]))
        out += ["", "## Network", "",
                f"{n['entities']} distinct entities ({mix}) resolved from {n['mentions']} mentions, "
                f"joined by {n['relationships']} relationships."]

    out += ["", "## Key individuals", ""]
    if not d["influencers"]:
        out.append("None identified yet.")
    for i in d["influencers"]:
        alias = f" (also written: {', '.join(i['aliases'])})" if i["aliases"] else ""
        flag = " — **needs review**" if i["needs_review"] else ""
        out += [f"{i['rank']}. **{i['name']}**{alias}{flag}", f"   - {i['reason']}",
                f"   - Source documents: {', '.join(i['documents']) or '—'}"]

    out += ["", "## Detected patterns", ""]
    out += [f"- **{a['type'].title()}** — {a['detail']}" + (f" (document {a['document']})" if a["document"] else "")
            for a in d["alerts"]] or ["No suspicious patterns detected."]

    out += ["", "## Entities awaiting review", ""]
    if not d["review"]:
        out.append("None — every merge was made on strong evidence.")
    for e in d["review"]:
        out += [f"- **{e['name']}** ({e['type']}, confidence {e['merge_confidence']}): "
                + "; ".join(e["reasons"][:3])]

    if d["overrides"]:
        out += ["", "## Investigator decisions", ""]
        out += [f"- {o['action'].replace('_', ' ')} ({o['created_at']})" + (f": {o['note']}" if o.get("note") else "")
                for o in d["overrides"]]
    return "\n".join(out) + "\n"


def to_csv(d: dict) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["entity", "type", "documents", "aliases", "merge_confidence", "needs_review", "reasons"])
    for e in d["entities"]:
        w.writerow([e["name"], e["type"], ";".join(e["documents"]), ";".join(e["aliases"]),
                    e["merge_confidence"], "yes" if e["needs_review"] else "no", " | ".join(e["reasons"])])
    if not d["entities"]:
        for s in d["sources"]:
            w.writerow([f"(source) {s['document_type']}", "document", s["count"], "", "", "", s["last_updated"]])
    return buf.getvalue()


def to_pdf(d: dict) -> bytes:
    from xml.sax.saxutils import escape

    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    styles = getSampleStyleSheet()
    small = ParagraphStyle("small", parent=styles["BodyText"], fontSize=8, leading=10, textColor=colors.HexColor("#444444"))
    body = ParagraphStyle("body", parent=styles["BodyText"], fontSize=9.5, leading=13)
    p = lambda text, style=body: Paragraph(escape(str(text)), style)  # noqa: E731 - escape user data

    c = d["case"]
    story = [Paragraph(escape(f"Case Summary — {c['title']}"), styles["Title"]),
             p(f"Case ID {c['id']}  ·  Status {c['status']}  ·  Opened {c['opened_at']}  ·  Generated {d['generated_at']}", small),
             Spacer(1, 4 * mm), p(DISCLAIMER, small), Spacer(1, 5 * mm)]

    def table(rows, widths):
        t = Table(rows, colWidths=widths, repeatRows=1)
        t.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
                               ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                               ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#9ca3af")),
                               ("VALIGN", (0, 0), (-1, -1), "TOP")]))
        return t

    story.append(Paragraph("Ingested sources", styles["Heading2"]))
    if d["sources"]:
        story.append(table([["Document type", "Count", "Last updated"]] +
                           [[s["document_type"], s["count"], s["last_updated"]] for s in d["sources"]],
                           [50 * mm, 25 * mm, 90 * mm]))
    else:
        story.append(p("No documents ingested for this case yet."))

    if d["counts"]:
        n = d["counts"]
        story += [Spacer(1, 4 * mm), Paragraph("Network", styles["Heading2"]),
                  p(f"{n['entities']} distinct entities resolved from {n['mentions']} mentions, "
                    f"joined by {n['relationships']} relationships.")]

    story += [Spacer(1, 4 * mm), Paragraph("Key individuals", styles["Heading2"])]
    if d["influencers"]:
        rows = [["#", "Individual", "Why flagged", "Source documents"]]
        for i in d["influencers"]:
            name = i["name"] + (f"\n(also: {', '.join(i['aliases'])})" if i["aliases"] else "") \
                + ("\n[needs review]" if i["needs_review"] else "")
            rows.append([i["rank"], Paragraph(escape(name), body), Paragraph(escape(i["reason"]), body),
                         Paragraph(escape(", ".join(i["documents"]) or "—"), small)])
        story.append(table(rows, [8 * mm, 42 * mm, 75 * mm, 45 * mm]))
    else:
        story.append(p("None identified yet."))

    story += [Spacer(1, 4 * mm), Paragraph("Detected patterns", styles["Heading2"])]
    story += [p(f"• {a['type'].title()} — {a['detail']}" + (f" (document {a['document']})" if a["document"] else ""))
              for a in d["alerts"]] or [p("No suspicious patterns detected.")]

    story += [Spacer(1, 4 * mm), Paragraph("Entities awaiting review", styles["Heading2"])]
    story += [p(f"• {e['name']} ({e['type']}, confidence {e['merge_confidence']}): " + "; ".join(e["reasons"][:3]))
              for e in d["review"]] or [p("None — every merge was made on strong evidence.")]

    buf = io.BytesIO()
    SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm,
                      bottomMargin=16 * mm, title=f"Case Summary — {c['title']}").build(story)
    return buf.getvalue()
